name: Swift
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: set -o pipefail && xcodebuild -project "Cluster.xcodeproj" -scheme "Example" CODE_SIGNING_ALLOWED=NO clean build | xcpretty
